version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore(deps,cargo)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps,github-actions)"
    ignore:
      - dependency-name: "dtolnay/rust-toolchain"
